# Generated by Django 5.2.8 on 2025-11-19 01:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula/DNI')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('ATRASADO', 'Atrasado')], default='ACTIVO', max_length=20)),
                ('score_crediticio', models.IntegerField(default=100, help_text='Puntaje calculado por el sistema (0-100)')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('frecuencia_dias', models.IntegerField(default=30, verbose_name='Frecuencia (días)')),
                ('pagada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.venta')),
            ],
        ),
    ]
