"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t_j6%5f#q!0)t-ipptsnt9ehl1!cx0+d49^jx@k300_r66aeg4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# ... (código anterior se mantiene igual) ...

# --- CONFIGURACIÓN REGIONAL (ESPAÑOL PARAGUAY) ---
LANGUAGE_CODE = 'es-py'  # Forzar español de Paraguay
TIME_ZONE = 'America/Asuncion'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Formato de números (Miles con punto)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3

# --- CONFIGURACIÓN VISUAL (JAZZMIN) ---
JAZZMIN_SETTINGS = {
    # Títulos y Logos
    "site_title": "Gestor de Cobranzas",
    "site_header": "Gestión",
    "site_brand": "💼 Mi Negocio",
    "welcome_sign": "Bienvenido al Sistema",
    "copyright": "MiGestor",
    
    # Buscador general (busca clientes directamente)
    "search_model": "gestion.Cliente",

    # BOTÓN PARA VOLVER A LA WEB (Punto 2 Solucionado)
    "topmenu_links": [
        {"name": "🏠 VOLVER AL DASHBOARD", "url": "dashboard", "permissions": ["auth.view_user"]},
    ],

    # Menú lateral simplificado
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Iconos para que se vea intuitivo
    "icons": {
        "gestion.Cliente": "fas fa-users",
        "gestion.Venta": "fas fa-shopping-cart",
        "gestion.Pago": "fas fa-hand-holding-usd",
        "auth.User": "fas fa-user-shield",
    },
    
    # Orden del menú
    "order_with_respect_to": ["gestion.Cliente", "gestion.Venta", "gestion.Pago"],
}

# --- TEMA VISUAL SUAVE (Punto 4 Solucionado) ---
JAZZMIN_UI_TWEAKS = {
    # Usamos 'spacelab' que es colores suaves (gris, azul, blanco)
    # Opciones buenas: 'spacelab', 'cerulean', 'cosmo', 'yeti'
    "theme": "spacelab", 
    
    # Desactivamos el modo oscuro forzado para evitar contrastes raros
    #"dark_mode_theme": None, 
    
    "navbar": "navbar-light",
    "sidebar": "sidebar-light-primary", # Barra lateral clara, no negra
}

# Configuración para la Nube
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
ALLOWED_HOSTS = ['*']